version: '3.8'


services:
  db:
    image: sameersbn/postgresql:10-2
    container_name: postgres
    environment:
      - DB_USER
      - DB_PASS
      - DB_NAME
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql

volumes:
  db_volume: