// Code generated by go-swagger; DO NOT EDIT.

package check

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new check API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for check API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GetGenerated(params *GetGeneratedParams, opts ...ClientOption) (*GetGeneratedOK, error)

	GetPDF(params *GetPDFParams, writer io.Writer, opts ...ClientOption) (*GetPDFOK, error)

	UpdateChecksStatus(params *UpdateChecksStatusParams, opts ...ClientOption) (*UpdateChecksStatusOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
GetGenerated gets a list of i ds of generated checks

This will return list of check IDs.
*/
func (a *Client) GetGenerated(params *GetGeneratedParams, opts ...ClientOption) (*GetGeneratedOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetGeneratedParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "getGenerated",
		Method:             "GET",
		PathPattern:        "/check/generated",
		ProducesMediaTypes: []string{"application/json", "application/pdf"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetGeneratedReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetGeneratedOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getGenerated: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetPDF gets pdf file for check

This will download pdf file of explicit check.
*/
func (a *Client) GetPDF(params *GetPDFParams, writer io.Writer, opts ...ClientOption) (*GetPDFOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetPDFParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "getPDF",
		Method:             "GET",
		PathPattern:        "/check/{check_id}/pdf",
		ProducesMediaTypes: []string{"application/pdf"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetPDFReader{formats: a.formats, writer: writer},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetPDFOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getPDF: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
UpdateChecksStatus updates status of some checks to be printed

This will update status of checks in DB to "printed".
*/
func (a *Client) UpdateChecksStatus(params *UpdateChecksStatusParams, opts ...ClientOption) (*UpdateChecksStatusOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUpdateChecksStatusParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "updateChecksStatus",
		Method:             "PUT",
		PathPattern:        "/check",
		ProducesMediaTypes: []string{"application/json", "application/pdf"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &UpdateChecksStatusReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*UpdateChecksStatusOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for updateChecksStatus: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
