// Code generated by go-swagger; DO NOT EDIT.

package check

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/pablogolobaro/chequery/cmd/client/models"
)

// GetGeneratedReader is a Reader for the GetGenerated structure.
type GetGeneratedReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetGeneratedReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetGeneratedOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetGeneratedInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetGeneratedOK creates a GetGeneratedOK with default headers values
func NewGetGeneratedOK() *GetGeneratedOK {
	return &GetGeneratedOK{}
}

/*
GetGeneratedOK describes a response with status code 200, with default header values.

List of generated checks ids
*/
type GetGeneratedOK struct {
	Payload *models.GeneratedChecksResponse
}

// IsSuccess returns true when this get generated o k response has a 2xx status code
func (o *GetGeneratedOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get generated o k response has a 3xx status code
func (o *GetGeneratedOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get generated o k response has a 4xx status code
func (o *GetGeneratedOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get generated o k response has a 5xx status code
func (o *GetGeneratedOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get generated o k response a status code equal to that given
func (o *GetGeneratedOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get generated o k response
func (o *GetGeneratedOK) Code() int {
	return 200
}

func (o *GetGeneratedOK) Error() string {
	return fmt.Sprintf("[GET /check/generated][%d] getGeneratedOK  %+v", 200, o.Payload)
}

func (o *GetGeneratedOK) String() string {
	return fmt.Sprintf("[GET /check/generated][%d] getGeneratedOK  %+v", 200, o.Payload)
}

func (o *GetGeneratedOK) GetPayload() *models.GeneratedChecksResponse {
	return o.Payload
}

func (o *GetGeneratedOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GeneratedChecksResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetGeneratedInternalServerError creates a GetGeneratedInternalServerError with default headers values
func NewGetGeneratedInternalServerError() *GetGeneratedInternalServerError {
	return &GetGeneratedInternalServerError{}
}

/*
GetGeneratedInternalServerError describes a response with status code 500, with default header values.

Generic server error
*/
type GetGeneratedInternalServerError struct {
	Payload *GetGeneratedInternalServerErrorBody
}

// IsSuccess returns true when this get generated internal server error response has a 2xx status code
func (o *GetGeneratedInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get generated internal server error response has a 3xx status code
func (o *GetGeneratedInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get generated internal server error response has a 4xx status code
func (o *GetGeneratedInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get generated internal server error response has a 5xx status code
func (o *GetGeneratedInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get generated internal server error response a status code equal to that given
func (o *GetGeneratedInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get generated internal server error response
func (o *GetGeneratedInternalServerError) Code() int {
	return 500
}

func (o *GetGeneratedInternalServerError) Error() string {
	return fmt.Sprintf("[GET /check/generated][%d] getGeneratedInternalServerError  %+v", 500, o.Payload)
}

func (o *GetGeneratedInternalServerError) String() string {
	return fmt.Sprintf("[GET /check/generated][%d] getGeneratedInternalServerError  %+v", 500, o.Payload)
}

func (o *GetGeneratedInternalServerError) GetPayload() *GetGeneratedInternalServerErrorBody {
	return o.Payload
}

func (o *GetGeneratedInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetGeneratedInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
GetGeneratedInternalServerErrorBody get generated internal server error body
swagger:model GetGeneratedInternalServerErrorBody
*/
type GetGeneratedInternalServerErrorBody struct {

	// The error message
	// Example: Error loading file
	// Required: true
	Message *string `json:"Message"`
}

// Validate validates this get generated internal server error body
func (o *GetGeneratedInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetGeneratedInternalServerErrorBody) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("getGeneratedInternalServerError"+"."+"Message", "body", o.Message); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this get generated internal server error body based on context it is used
func (o *GetGeneratedInternalServerErrorBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetGeneratedInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetGeneratedInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res GetGeneratedInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
