// Code generated by go-swagger; DO NOT EDIT.

package check

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetPDFReader is a Reader for the GetPDF structure.
type GetPDFReader struct {
	formats strfmt.Registry
	writer  io.Writer
}

// ReadResponse reads a server response into the received o.
func (o *GetPDFReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPDFOK(o.writer)
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetPDFInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetPDFOK creates a GetPDFOK with default headers values
func NewGetPDFOK(writer io.Writer) *GetPDFOK {
	return &GetPDFOK{

		Payload: writer,
	}
}

/*
GetPDFOK describes a response with status code 200, with default header values.

Pdf file of check
*/
type GetPDFOK struct {
	Payload io.Writer
}

// IsSuccess returns true when this get p d f o k response has a 2xx status code
func (o *GetPDFOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get p d f o k response has a 3xx status code
func (o *GetPDFOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get p d f o k response has a 4xx status code
func (o *GetPDFOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get p d f o k response has a 5xx status code
func (o *GetPDFOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get p d f o k response a status code equal to that given
func (o *GetPDFOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetPDFOK) Error() string {
	return fmt.Sprintf("[GET /check/{check_id}/pdf][%d] getPDFOK  %+v", 200, o.Payload)
}

func (o *GetPDFOK) String() string {
	return fmt.Sprintf("[GET /check/{check_id}/pdf][%d] getPDFOK  %+v", 200, o.Payload)
}

func (o *GetPDFOK) GetPayload() io.Writer {
	return o.Payload
}

func (o *GetPDFOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPDFInternalServerError creates a GetPDFInternalServerError with default headers values
func NewGetPDFInternalServerError() *GetPDFInternalServerError {
	return &GetPDFInternalServerError{}
}

/*
GetPDFInternalServerError describes a response with status code 500, with default header values.

Generic server error
*/
type GetPDFInternalServerError struct {
	Payload *GetPDFInternalServerErrorBody
}

// IsSuccess returns true when this get p d f internal server error response has a 2xx status code
func (o *GetPDFInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get p d f internal server error response has a 3xx status code
func (o *GetPDFInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get p d f internal server error response has a 4xx status code
func (o *GetPDFInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get p d f internal server error response has a 5xx status code
func (o *GetPDFInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get p d f internal server error response a status code equal to that given
func (o *GetPDFInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *GetPDFInternalServerError) Error() string {
	return fmt.Sprintf("[GET /check/{check_id}/pdf][%d] getPDFInternalServerError  %+v", 500, o.Payload)
}

func (o *GetPDFInternalServerError) String() string {
	return fmt.Sprintf("[GET /check/{check_id}/pdf][%d] getPDFInternalServerError  %+v", 500, o.Payload)
}

func (o *GetPDFInternalServerError) GetPayload() *GetPDFInternalServerErrorBody {
	return o.Payload
}

func (o *GetPDFInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetPDFInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
GetPDFInternalServerErrorBody get p d f internal server error body
swagger:model GetPDFInternalServerErrorBody
*/
type GetPDFInternalServerErrorBody struct {

	// The error message
	// Example: Error loading file
	// Required: true
	Message *string `json:"Message"`
}

// Validate validates this get p d f internal server error body
func (o *GetPDFInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetPDFInternalServerErrorBody) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("getPDFInternalServerError"+"."+"Message", "body", o.Message); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this get p d f internal server error body based on context it is used
func (o *GetPDFInternalServerErrorBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetPDFInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetPDFInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res GetPDFInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
