// Code generated by go-swagger; DO NOT EDIT.

package check

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetGeneratedParams creates a new GetGeneratedParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetGeneratedParams() *GetGeneratedParams {
	return &GetGeneratedParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetGeneratedParamsWithTimeout creates a new GetGeneratedParams object
// with the ability to set a timeout on a request.
func NewGetGeneratedParamsWithTimeout(timeout time.Duration) *GetGeneratedParams {
	return &GetGeneratedParams{
		timeout: timeout,
	}
}

// NewGetGeneratedParamsWithContext creates a new GetGeneratedParams object
// with the ability to set a context for a request.
func NewGetGeneratedParamsWithContext(ctx context.Context) *GetGeneratedParams {
	return &GetGeneratedParams{
		Context: ctx,
	}
}

// NewGetGeneratedParamsWithHTTPClient creates a new GetGeneratedParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetGeneratedParamsWithHTTPClient(client *http.Client) *GetGeneratedParams {
	return &GetGeneratedParams{
		HTTPClient: client,
	}
}

/*
GetGeneratedParams contains all the parameters to send to the API endpoint

	for the get generated operation.

	Typically these are written to a http.Request.
*/
type GetGeneratedParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get generated params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetGeneratedParams) WithDefaults() *GetGeneratedParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get generated params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetGeneratedParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get generated params
func (o *GetGeneratedParams) WithTimeout(timeout time.Duration) *GetGeneratedParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get generated params
func (o *GetGeneratedParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get generated params
func (o *GetGeneratedParams) WithContext(ctx context.Context) *GetGeneratedParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get generated params
func (o *GetGeneratedParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get generated params
func (o *GetGeneratedParams) WithHTTPClient(client *http.Client) *GetGeneratedParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get generated params
func (o *GetGeneratedParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetGeneratedParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
