// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GeneratedChecksResponse generated checks response
//
// swagger:model GeneratedChecksResponse
type GeneratedChecksResponse struct {

	// i ds
	// Example: [1,2,3]
	IDs []int64 `json:"ids"`
}

// Validate validates this generated checks response
func (m *GeneratedChecksResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this generated checks response based on context it is used
func (m *GeneratedChecksResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GeneratedChecksResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GeneratedChecksResponse) UnmarshalBinary(b []byte) error {
	var res GeneratedChecksResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
