// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OrderCreateResponse order create response
//
// swagger:model OrderCreateResponse
type OrderCreateResponse struct {

	// ids
	// Example: [1,2,3]
	Ids []int64 `json:"ids"`
}

// Validate validates this order create response
func (m *OrderCreateResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this order create response based on context it is used
func (m *OrderCreateResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OrderCreateResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrderCreateResponse) UnmarshalBinary(b []byte) error {
	var res OrderCreateResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
